services:
  postgres:
    image: postgres:17
    container_name: bestfly-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: best_fly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bestfly-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.6
    container_name: bestfly-redis
    ports:
      - "6379:6379"
    volumes:
      - bestfly-redis-data:/data

  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  bestfly-postgres-data:
  bestfly-redis-data:
