services:
  postgres:
    image: postgres:17
    container_name: bestfly-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: best_fly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bestfly-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.6
    container_name: bestfly-redis
    ports:
      - "6379:6379"
    volumes:
      - bestfly-redis-data:/data

volumes:
  bestfly-postgres-data:
  bestfly-redis-data:
