spring.application.name=Best Fly

history.retentionDays=90
history.cleanupCron=0 0 3 * * *

duffel.token=${DUFFEL_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/best_fly

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET}

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s

server.forward-headers-strategy=native
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enabled=true
# Base URL used by OpenAPI/Swagger UI when behind a reverse proxy (set to your public domain)
app.openapi.server-url=https://bestflyapi.duckdns.org